fos_rest:
    view:
        view_response_listener: true
    body_listener:
        enabled: true
    format_listener:
        rules:
          - { host: api.fenrir-studio.fr, path: ^/, prefer_extension: true, fallback_format: json }
          - { host: admin.fenrir-studio.fr, path: ^/, priorities: [ html ] , fallback_format: html }