security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:             ROLE_USER
        ROLE_SUPER_ADMIN:       ROLE_ADMIN

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            host: api\.fenrir-studio\.fr
            pattern: ^/login
            stateless: true
            anonymous: true
            json_login:
                check_path: /login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        auth_register:
            host: admin\.fenrir-studio\.fr
            pattern: ^/auth/register
            stateless: true
            anonymous: true
            provider: fos_userbundle
        api:
            host: api\.fenrir-studio\.fr
            pattern: ^/
            stateless: true
            anonymous: true
            provider: fos_userbundle
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        main:
            host: admin\.fenrir-studio\.fr
            access_denied_handler: App\Security\AccessDeniedHandler
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:     true
            anonymous:  true


    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY , host: admin\.fenrir-studio\.fr }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY , host: admin\.fenrir-studio\.fr}
        - { path: ^/, role: ROLE_ADMIN, host: admin\.fenrir-studio\.fr }
        - { path: ^/formation, role: ROLE_USER, host: api\.fenrir-studio\.fr }
        - { path: ^/survey, role: ROLE_USER, host: api\.fenrir-studio\.fr }
        - { path: ^/survey/new, role: IS_AUTHENTICATED_FULLY, host: api\.fenrir-studio\.fr }
        - { path: ^/formation/new, role: ROLE_USER, host: api\.fenrir-studio\.fr }
        - { path: ^/formation, role: ROLE_ADMIN, host: admin\.fenrir-studio\.fr }
        - { path: ^/event, role: IS_AUTHENTICATED_ANONYMOUSLY, host: admin\.fenrir-studio\.fr }
        - { path: ^/users, role: ROLE_ADMIN, host: admin\.fenrir-studio\.fr }
        - { path: ^/admin, role: ROLE_ADMIN, host: admin\.fenrir-studio\.fr }
        - { path: ^/redirectionTo, role: IS_AUTHENTICATED_FULLY, host: admin\.fenrir-studio\.fr }
        - { path: ^/event, role: IS_AUTHENTICATED_ANONYMOUSLY, host: api\.fenrir-studio\.fr }
        #- { path: ^/auth, role: IS_AUTHENTICATED_ANONYMOUSLY, host: api\.connexion\.fr}
        - { path: ^/actu, role: IS_AUTHENTICATED_ANONYMOUSLY, host: admin\.fenrir-studio\.fr }
        - { path: ^/actu, role: IS_AUTHENTICATED_ANONYMOUSLY, host: api\.fenrir-studio\.fr }
        - { path: ^/product, role: IS_AUTHENTICATED_ANONYMOUSLY, host: api\.fenrir-studio\.fr }