swiftmailer:
    delivery_addresses: ['leosouly@gmail.com']
    transport: smtp
    encryption: ssl
    host: smtp.gmail.com
    username: leosouly@gmail.com
    password: Persephonelayer33
    spool: { type: 'memory' }
