to_ng:
    path: /
    host: 'localhost:4200'
    defaults:
        url: 'localhost:4200/login'

controllers:
    host: 'admin.fenrir-studio.fr'
    resource: ../../src/Controller/
    type: annotation

api_auth_login:
    host: 'api.fenrir-studio.fr'
    path: /login_check
    methods: [POST]

api_controllers:
    host: 'api.fenrir-studio.fr'
    resource: ../../src/ApiController/
    type: annotation
