<?php

namespace App\ApiController;

use App\Entity\Image;
use App\Form\ImageType;
use App\Event\ImageCreatedEvent;
use Symfony\Component\EventDispatcher\EventDispatcherInterface;
use App\Repository\ImageRepository;
use Doctrine\Common\Collections\ArrayCollection;
use FOS\RestBundle\Controller\Annotations as Rest;
use FOS\RestBundle\Controller\AbstractFOSRestController;
use FOS\RestBundle\View\View;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Response;

/**
 * @Route("/image", host="api.connexion.fr")
 */
class ImageController extends AbstractFOSRestController
{
    protected $dispatcher;
    public function __construct(EventDispatcherInterface $dispatcher)
    {
        $this->dispatcher = $dispatcher;
    }
    /**
     * @Rest\Get(
     * path = "/",
     * name="image_api",
     * )
     * @Rest\View()
     */
    public function index(ImageRepository $imageRepository): View
    {
        $image = $imageRepository->findAll();
        return View::create($image, Response::HTTP_OK);
    }

    /**
     * @Rest\Get(
     * path = "/{id}",
     * name="imageshow_api",
     * )
     * @Rest\View()
     */
    public function show(Image $image): View
    {
        return View::create($image, Response::HTTP_OK);
    }

    /**
     * @Rest\Post(
     * path = "/new",
     * name="imagenew_api",
     * )
     * @Rest\View()
     */
    public function create(Request $request): View
    {

        $image = new Image();
        $file = $request->files->get('file');
        
        if ($file){
            $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();

            // Move the file to the directory where brochures are stored
            try {
                $file->move(
                    $this->getParameter('images_directory'),
                    $fileName
                );
            } catch (FileException $e) {
                // ... handle exception if something happens during file upload
            }
            // updates the 'brochure' property to store the PDF file name
            // instead of its contents
            $image->setPath($this->getParameter('images_directory').'/'.$fileName);
            $image->setImgPath($this->getParameter('images_path').'/'.$fileName);
            $image->setAllowed(false);
            //$image->setTitle($request->get('title'));
            $image->setDescription($request->get('description'));
            
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($image);
            $entityManager->flush();
            $imageEvent = new ImageCreatedEvent($image);
            $this->dispatcher->dispatch('image.created', $imageEvent);
            
        }

        return View::create($image, Response::HTTP_CREATED);
    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }

    /**
     * @Rest\Put(
     * path = "/{id}",
     * name="imageedit_api",
     * )
     * @Rest\View()
     */
    public function edit(Request $request,Image $image): View
    {
        if($image) {
            $image->setPath($request->get('path'));
            $image->setImgPath($request->get('imgPath'));
            $em = $this->getDoctrine()->getManager();
            $em->persist($image);
            $em->flush();
        }
        return View::create($image, Response::HTTP_CREATED);

    }

    /**
     * @Rest\Patch(
     * path = "/{id}",
     * name="imagepatch_api",
     * )
     * @Rest\View()
     */
    public function patch(Request $request,Image $image): View
    {
        if($image) {
            $form = $this->createForm(ImageType::class, $image);
            $form->submit($request->request->all(), false);
            $em = $this->getDoctrine()->getManager();
            $em->persist($image);
            $em->flush();
        }
        return View::create($image, Response::HTTP_CREATED);

    }

    /**
     * @Rest\Delete(
     *   path="/{id}",
     *   name="imagedelete_api",
     * )
     * @Rest\View()
     */
    public function delete(Image $image): View
    {
        if ($image) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($image);
            $entityManager->flush();
        }

        return View::create([], Response::HTTP_NO_CONTENT);
    }
}