#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#api_auth_login:
#    path: api.connexion.fr/login
#    methods: [POST]
#
#api:
#    #prefix: /api
#    resource: '../src/ApiController'
